## Autogenerated config.py
## Documentation:
##   qute://help/configuring.html
##   qute://help/settings.html

import subprocess

def read_xresources(prefix):
    props = {}
    x = subprocess.run(['xrdb', '-query'], stdout=subprocess.PIPE)
    lines = x.stdout.decode().split('\n')
    for line in filter(lambda l : l.startswith(prefix), lines):
        prop, _, value = line.partition(':\t')
        props[prop] = value
    return props

xresources = read_xresources('*')

config.load_autoconfig()

c.colors.completion.category.bg = xresources['*color6']
c.colors.completion.category.fg = xresources['*background']

c.colors.completion.category.border.bottom = xresources['*background']
c.colors.completion.category.border.top = xresources['*color6']

c.colors.completion.even.bg = xresources['*background']

c.colors.completion.odd.bg = xresources['*background']

c.colors.completion.item.selected.bg = xresources['*color4']
c.colors.completion.item.selected.fg = xresources['*foreground']

c.colors.completion.item.selected.border.bottom = xresources['*color4']

c.colors.completion.match.fg = xresources['*color2']

c.colors.completion.scrollbar.bg = xresources['*foreground']
c.colors.completion.scrollbar.fg = xresources['*background']

c.colors.downloads.bar.bg = xresources['*background']

c.colors.downloads.error.bg = xresources['*color1']
c.colors.downloads.error.fg = xresources['*foreground']

c.colors.downloads.start.bg = xresources['*color5']
c.colors.downloads.start.fg = xresources['*foreground']

c.colors.downloads.stop.bg = xresources['*color2']
c.colors.downloads.stop.fg = xresources['*foreground']

c.colors.hints.bg = xresources['*background']
c.colors.hints.fg = xresources['*foreground']

c.colors.hints.match.fg = xresources['*color3']

c.colors.keyhint.bg = xresources['*background']
c.colors.keyhint.fg = xresources['*foreground']

c.colors.keyhint.suffix.fg = xresources['*color3']

c.colors.messages.error.bg = xresources['*color1']
c.colors.messages.error.border = xresources['*color1']
c.colors.messages.error.fg = xresources['*foreground']

c.colors.messages.info.bg = xresources['*color2']
c.colors.messages.info.border = xresources['*color2']
c.colors.messages.info.fg = xresources['*foreground']

c.colors.messages.warning.bg = xresources['*color3']
c.colors.messages.warning.border = xresources['*color3']
c.colors.messages.warning.fg = xresources['*foreground']

c.colors.prompts.bg = xresources['*background']
c.colors.prompts.border = xresources['*background']
c.colors.prompts.fg = xresources['*foreground']

c.colors.prompts.selected.bg = xresources['*color3']

c.colors.statusbar.caret.bg = xresources['*color5']
c.colors.statusbar.caret.fg = xresources['*foreground']

c.colors.statusbar.command.bg = xresources['*color6']
c.colors.statusbar.command.fg = xresources['*background']

c.colors.statusbar.command.private.bg = 'black'

c.colors.statusbar.insert.bg = xresources['*color2']
c.colors.statusbar.insert.fg = xresources['*foreground']

c.colors.statusbar.normal.bg = xresources['*background']
c.colors.statusbar.normal.fg = xresources['*foreground']

c.colors.statusbar.private.bg = xresources['*background']
c.colors.statusbar.private.fg = xresources['*foreground']

c.colors.statusbar.progress.bg = xresources['*foreground']

c.colors.statusbar.url.error.fg = xresources['*color1']

c.colors.statusbar.url.fg = xresources['*foreground']

c.colors.statusbar.url.hover.fg = xresources['*color4']

c.colors.statusbar.url.success.http.fg = xresources['*foreground']

c.colors.statusbar.url.success.https.fg = xresources['*color2']

c.colors.statusbar.url.warn.fg = xresources['*color3']

c.colors.tabs.bar.bg = xresources['*background']

c.colors.tabs.even.bg = xresources['*background']
c.colors.tabs.even.fg = xresources['*foreground']

c.colors.tabs.odd.bg = xresources['*background']
c.colors.tabs.odd.fg = xresources['*foreground']

c.colors.tabs.selected.even.bg = xresources['*foreground']
c.colors.tabs.selected.even.fg = xresources['*background']

c.colors.tabs.selected.odd.bg = xresources['*foreground']
c.colors.tabs.selected.odd.fg = xresources['*background']

c.colors.webpage.bg = xresources['*foreground']

c.hints.border = '1px solid ' + xresources['*foreground']

c.statusbar.hide = True
c.tabs.show = 'multiple'

c.content.geolocation = False

c.editor.command = ['urxvt', '-e', '/home/micah/.config/i3/scripts/runner', 'nvim', '{}']

c.qt.args = ['ppapi-widevine-path=/usr/lib/qt/plugins/ppapi/libwidevinecdmadapter.so', 'disable-seccomp-filter-sandbox']

c.url.searchengines["aw"] = "https://wiki.archlinux.org/?search={}"
c.url.searchengines["az"] = "https://www.amazon.com/s/?field-keywords={}"
c.url.searchengines["d"] = "https://duckduckgo.com/?q={}"
c.url.searchengines["g"] = "https://www.google.com/search?hl=en&q={}"
c.url.searchengines["rd"] = "https://reddit.com/r/{}"
c.url.searchengines["yt"] = "https://youtube.com/results?search_query={}"
c.url.searchengines["DEFAULT"] = c.url.searchengines["g"]

config.bind(',al', ':open https://www.reddit.com/me/m/alllinux/new')
config.bind(',az', ':open https://amazon.com')
config.bind(',bp', ':open https://buzzport.gatech.edu/cp/home/displaylogin')
config.bind(',cl', ':open https://calendar.google.com')
config.bind(',cv', ':open https://gatech.instructure.com')
config.bind(',et', ':open https://etime.gtri.gatech.edu/DeltekTC/welcome.msv')
config.bind(',fb', ':open https://facebook.com')
config.bind(',gh', ':open https://github.com/mehalter')
config.bind(',gl', ':open https://gitlab.com/dashboard/projects')
config.bind(',kp', ':open https://keep.google.com')
config.bind(',ml', ':open https://mail.google.com')
config.bind(',mp', ':open https://maps.google.com')
config.bind(',ms', ':open https://play.google.com/music/listen')
config.bind(',nf', ':open https://netflix.com')
config.bind(',pj', ':open https://github.gatech.edu/HFPE/hfpe-web/projects/1')
config.bind(',pz', ':open https://piazza.com')
config.bind(',rd', ':open http://reddit.com')
config.bind(',sm', ':open https://outlook.office.com/owa/?realm=gatech.edu')
config.bind(',ts', ':open http://tsquare.gatech.edu')
config.bind(',tv', ':open http://tv.youtube.com')
config.bind(',wm', ':open https://sso.gtri.gatech.edu/adfs/ls/?wa=wsignin1.0&wtrealm=https%3a%2f%2fmail.gtri.gatech.edu%2fowa%2f&wctx=rm%3d0%26id%3dpassive%26ru%3d%252fowa%252f&wct=2016-01-29T15%3a00%3a27Z')
config.bind(',ws', ':open http://mehalter.com')
config.bind(',yt', ':open https://youtube.com')

config.bind(';m', 'hint links spawn mpv {hint-url}')

config.bind('J', ':tab-prev')
config.bind('K', ':tab-next')
config.bind('D', ':close')
config.bind('I', ':open -p')
config.bind('W', ':tab-give')
config.bind('t', ':open -t')
config.bind('xb', ':config-cycle statusbar.hide')
config.bind('xt', ':config-cycle tabs.show multiple switching')
