#!/bin/bash

lookup=$1
action=$2
format=$3
font=$4

chosen=$(sed -n 's/^\([^:]*\):.*$/\1/p' $lookup|dmenu $format -fn "$font")

expanded=$(sed -n "s/^${chosen}:\(.*\)$/\1/p" $lookup)
[ "$expanded" != "" ] && $action $expanded
