#!/bin/bash

if [[ -d ~/.Mail ]]; then
  out=$(find ~/.Mail/Gatech/INBOX/new ~/.Mail/Gmail/INBOX/new -type f|wc -l)

  if [ "$out" != "0" ]; then
    echo $out
  else
    echo ""
  fi
else
  echo ""
fi
