#!/bin/bash

LAYOUT=`setxkbmap -query | awk '
    BEGIN{layout="";variant=""}
    /^layout/{layout=$2}
    /^variant/{variant=" ("$2")"}
    END{printf("%s%s",layout,variant)}'`

if [ "$LAYOUT" == "us" ]; then
    echo "us"
elif [ "$LAYOUT" == "dvorak" ]; then
    echo "dvo"
fi
