#!/usr/bin/env bash

# Source generated colors.
. "${HOME}/.cache/wal/colors.sh"

reload_dunst() {
    pkill dunst
    dunst \
        -lb "${color1:-#FFFFFF}" \
        -nb "${color1:-#FFFFFF}" \
        -cb "${color1:-#FFFFFF}" \
        -lf "${color0:-#000000}" \
        -bf "${color0:-#000000}" \
        -cf "${color0:-#000000}" \
        -nf "${color0:-#000000}" \
        -geometry "300x5-10+34" &
}

reload_qute() {
  python3 /home/micah/.config/Scripts/qutebrowser_reload.py
}

main() {
    reload_dunst
    reload_qute
}

main
