#!/usr/bin/env bash

# Source generated colors.
. "${HOME}/.cache/wal/colors.sh"

reload_dunst() {
    pkill dunst
    dunst \
        -lb "${background:-#FFFFFF}" \
        -nb "${background:-#FFFFFF}" \
        -cb "${background:-#FFFFFF}" \
        -lf "${foreground:-#000000}" \
        -bf "${foreground:-#000000}" \
        -cf "${foreground:-#000000}" \
        -nf "${foreground:-#000000}" \
        -geometry "300x5-10+34" &
}

reload_qute() {
  python3 /home/micah/.config/Scripts/qutebrowser_reload.py
}

main() {
    reload_dunst
    reload_qute
}

main
